services:
  web-svc:
    image: nginx
    ports:
      - "8080:80"
  login-svc:
    image: ravi2krishna/login-2502
    ports:
      - "8081:80"
  food-svc:
    build: ./food
    image: ravi2krishna/food
    ports:
      - "8082:80"
  ecomm-svc:
    image: nginx
    volumes:
      - /home/ubuntu/app-services/ecomm:/usr/share/nginx/html
    ports:
      - "8083:80"
