apiVersion: v1
kind: Pod
metadata:
  name: multi-pod-works
spec:
  contianers: 
  - name: container-1
    image: nginx
    ports: 
    - contianerPort: 80
  - name: ubuntu
    image: ubuntu
    command: ["sleep"]
    args: ["300"]